on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}

      - uses: google-github-actions/release-please-action@v4
        id: releaes-please
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: rust
          skip-github-release: true

      - name: Check head commit message
        run: |
          echo "HEAD commit message: '${{ github.event.head_commit.message }}'"

      - name: Tagging
        if: "${{ startsWith('chore(main): release', github.event.head_commit.message) }}"
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const m = '${{ github.event.head_commit.message }}'.match(/^chore\(main\): release (\d+\.\d+.\d+) \(#\d+\)$/)
            if (!m || m.length < 2) {
              return
            }
            const version = m[1]
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${version}`,
              sha: context.sha
            })
